### ISSUE TITLE
Broken push subscriptions

### ISSUE THREAD

**Issue by dennisreimann** [alexbosworth/ln-service#108]
I upgraded ln-service this week and found that [the introduction of named events](https://github.com/alexbosworth/ln-service/blob/master/CHANGELOG.md#breaking-changes-6) (98c68ba15ea025b1203bb97dc16bbb344904e417) seems to have broken the push subscriptions like for [transactions](https://github.com/alexbosworth/ln-service/blob/master/push/transactions.js#L31), [invoices](https://github.com/alexbosworth/ln-service/blob/master/push/invoices.js#L32) and [graph](https://github.com/alexbosworth/ln-service/blob/master/push/graph.js#L31). 

These subscribe on the `data` events, but since the updates those do not seem to get emitted anymore – their data source in the `lightning` folder (i.e. for [transactions](https://github.com/alexbosworth/ln-service/blob/master/lightning/subscribe_to_transactions.js#L58)) gets the `data` event from the upstream lnd socket connection, but emits a named event which is not received by the downstream connection. Thus the subscriptions in the [server](https://github.com/alexbosworth/ln-service/blob/master/server.js#L128) are also broken.

Maybe I misunderstood something, but from testing this in my app and the rest server in this repo the subscriptions worked before. Monkey-patching the code and subscribing i.e. to `'channel_updated'` (events recieved) instead of `'data'` (no events received) in the `push/graph` module also indicates that it is currently broken.

**Comment by alexbosworth** [comment]
I think it is broken, the REST proxy overall needs to be revamped

**Comment by alexbosworth** [comment]
Should be fixed in 47.5.3

**Comment by dennisreimann** [comment]
Thanks, it's working now! 👍

Unrelated to the original error, but now I get `Error: 2 UNKNOWN: router not started` when I start my app server. Any pointers for that? Maybe it's related to the "Requires LND built with `routerrpc` build tag" hints in the README?

**Comment by alexbosworth** [comment]
Great. I have a more conclusive solution in mind to the REST proxy but I haven't found time implement it

I believe that error is related to doing a subscription or call to the API before LND is fully started and is a relatively benign error where you can just retry
