### ISSUE TITLE
Add main entry point exposing `/lightning` directory

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#11]
- [x] Add an `lightning_adapter.js`
- [x] Allow specifying a config file
- [x] Move what can be configurable to the base config file
- [x] Add main in package.json
- [x] Expose services
- [x] Refactor the server to use the adapter

I will submit a PR in a few.

**Comment by alexbosworth** [comment]
Take a look at a847a8e14aaf5e2121b2efd647ad370be740d369 I also took a stab at this

**Comment by PWKad** [comment]
Ah I see what you mean so instead of accepting parameters to specify config just take it as parameters makes since I'll pull master and try it out

**Comment by alexbosworth** [comment]
I need to document it a bit better but what you need to do is to do `$ base64 admin.macaroon` and `base64 tls.cert` in order to get the appropriate values for lightning_daemon.js

**Comment by alexbosworth** [comment]
You also need to pass like `localhost:10009` as the host, I didn't set that up as the default

**Comment by PWKad** [comment]
So I've been reviewing and I think the server should be broke until the cert and key are passed in so I'll make that PR.
