### ISSUE TITLE
Unexpected error when paying via route

### ISSUE THREAD

**Issue by apotdevin** [alexbosworth/ln-service#110]
Trying to make a circular payment I was getting an unexpected error. Decided to try from the basic of paying via a route as shown in the documentation with:
```
const {getRoutes, payViaRoutes} = require('ln-service');
const destination = 'destinationPublicKeyHexString';
const tokens = 80085;
const {routes} = await getRoutes({destination, lnd, tokens});
const preimage = (await payViaRoutes({lnd, routes})).secret;
```

but keep getting:
```
[
  503,
  'UnexpectedErrorWhenPayingViaRoute',
  {
    failures: [
      [
        503,
        'UnexpectedErrorWhenPayingViaRoute',
        { err: [Error] },
        [length]: 3
      ],
      [length]: 1
    ]
  },
  [length]: 3
]
```

Don't know what i'm missing here

**Comment by alexbosworth** [comment]
This may be a better example to go off of for a circular payment: https://github.com/alexbosworth/ln-service/blob/master/test/integration/test_rebalance.js

**Comment by apotdevin** [comment]
Great, tested it and payment goes through when I only do one hop (Control node -> Target Node -> Control node).

For a longer path any recommended way to get the route? Since the getRoute example in this link would give me only a one hop route as above

**Comment by alexbosworth** [comment]
Here is a more complex example of rebalancing: https://github.com/alexbosworth/balanceofsatoshis/blob/master/swaps/rebalance.js

**Comment by apotdevin** [comment]
Will have a look! Thanks

**Comment by apotdevin** [comment]
Excited to try out the in house channel balancing coming with LND 9

**Comment by alexbosworth** [comment]
The 0.9.0 circular rebalancing works a bit differently so I've split the getRoutes method into two methods: getRoutes and getRouteToDestination in order to support both methods
