### ISSUE TITLE
node events: on versus once

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#113]
Looking at: https://github.com/alexbosworth/ln-service#subscribeToInvoices

The code is: 

```
const {once} = require('events');
const {subscribeToInvoices} = require('ln-service');
const sub = subscribeToInvoices({lnd});
const [lastUpdatedInvoice] = await once(sub, 'invoice_updated');
```

As we want to listen to invoice**s**, shouldn't it be {on} instead of {once} ?

as a side note, the use of await make the code not copy/pastable for the following reason:
`'await' expression is only allowed within an async function.` (I know the workaround)

**Comment by alexbosworth** [comment]
Yep, this is more of a complete example https://github.com/alexbosworth/ln-service/blob/master/test/integration/test_subscribe_to_invoices.js#L90

**Comment by nicolasburtey** [comment]
thanks. feel free to close the issue as you wish, it was a suggestion for documentation improvement.
