### ISSUE TITLE
Error type?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#116]
I tried the following:

```
try {
        await lnService.payViaPaymentDetails(request)
} catch (err) {
        console.log(typeof err)
}
```

I have `object` as the result ( the object being [ 503, 'FailedToFindPayableRouteToDestination' ] in this case )

Why not extending Error instead? This seems to be the recommended way when looking at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error

**Comment by alexbosworth** [comment]
Just personal preference, I find it easier to write this array

**Comment by nicolasburtey** [comment]
ok
