### ISSUE TITLE
Use ln-service to connect to my personal node (throught Tor) 

### ISSUE THREAD

**Issue by louneskmt** [alexbosworth/ln-service#117]
Hi,

I would like to know how I can do to connect to my LN node (not hosted locally), throught Tor (if possible, otherwise without) ? With which build tags do I need to compile lnd ? And what should my lnd.conf file look like ?

I ideally want to connect to my node, to pay and generate invoices.

Thanks a lot for your package, it seems really awesome !

Lounès

**Comment by alexbosworth** [comment]
I have some suggested build tags and Tor settings here: https://github.com/alexbosworth/run-lnd/blob/master/README.md#install-lnd

You can run your node on Tor for connecting peer to peer and then use the normal networking for remote controlling it

**Comment by lounes-kmt** [comment]
Thanks for the link, I couldn't find it before ! Gonna check that 👌
