### ISSUE TITLE
Error getting utxos

### ISSUE THREAD

**Issue by apotdevin** [alexbosworth/ln-service#123]
Calling `const {utxos} = await getUtxos({lnd});` gives me the following error:

```
[
  503,
  'UnexpectedErrorGettingUtxos',
  {
    err: Error: 1 CANCELLED: Received http2 header with status: 404 ......
]
```

This is with LND 0.10.2

Tried with 0.10.1 and it seems to work 🤔

**Comment by alexbosworth** [comment]
That's weird, did you try any other versions?

**Comment by alexbosworth** [comment]
Can you check that you compiled LND 0.10.2 with `walletrpc`?

**Comment by alexbosworth** [comment]
Ah this may be the issue, since the default rpc method is being eliminated

**Comment by alexbosworth** [comment]
I updated things to be more forgiving about the error message, does this fix it?

**Comment by apotdevin** [comment]
Awesome, updated and the getUtxos works! just gives a warning `Warning: possibly corrupted metadata key received: :status: 404. Please report this at https://github.com/grpc/grpc-node/issues/1173.  `

But now when I went to check if the `walletrpc` was available with `getWalletVersion` it gave a similar error as above:
```
[
  503,
  'UnexpectedGetWalletVersion',
  {
    err: Error: 1 CANCELLED: Received http2 header with status: 404....
]
```

This again happened with 0.10.2 and works fine with 0.10.1

**Comment by alexbosworth** [comment]
That method should be supported but it's giving back an error

It seems like something may be wrong on your side, is the only thing you are changing the release tag?

**Comment by apotdevin** [comment]
hmm I'm not sure what it was but it seems to be working now.. LND version is still the same, weird. Closing this! Thanks for the support
