### ISSUE TITLE
getRoutes should take `payment` as an argument?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#129]
I'm calling `getRoutes({ destination, lnd, tokens, routes })` and get the following result: 

```
routes: [
        {
          confidence: 950000,
          fee: 0,
          fee_mtokens: '0',
          hops: [
            {
              channel: '148x1x0',
              channel_capacity: 10000000,
              fee: 0,
              fee_mtokens: '0',
              forward: 1000,
              forward_mtokens: '1000000',
              public_key: '02424d23299ba8ddaf2becbc204092d8a3e9686bb933188a8a6ed523de7e2c67e7',
              timeout: 205
            }
          ],
          mtokens: '1000000',
          payment: undefined,
          safe_fee: 0,
          safe_tokens: 1000,
          timeout: 205,
          tokens: 1000,
          total_mtokens: undefined
        }
      ]
```

I can replace `payment` after I have the result, but being able to pass `payment` from a `decodePaymentRequest` directly to a getRoutes would feel more logical.

**Comment by alexbosworth** [comment]
I would use `getRouteToDestination`

**Comment by nicolasburtey** [comment]
oh yeah I missed this one.

Why do we have 2 methods? different API versions?

**Comment by alexbosworth** [comment]
> oh yeah I missed this one.
> 
> Why do we have 2 methods? different API versions?

Yes, the API was changed in a way where compatibility couldn't be maintained with the old behavior and the outcome of the API also changed to only return a single route when before it returned multiple routes

**Comment by nicolasburtey** [comment]
oh ok. this is why I had been using getRoutes then, to get a list of multiple routes and probe them one by one.
is there a way to iterate over routes with `getRouteToDestination`?

**Comment by alexbosworth** [comment]
> oh ok. this is why I had been using getRoutes then, to get a list of multiple routes and probe them one by one.
> is there a way to iterate over different possible routes with `getRouteToDestination`?

It should work exactly the same way, on versions of LND later than 0.8.2 both methods will return pretty much the same thing, a single route to attempt and then iterate with

**Comment by nicolasburtey** [comment]
`getRoutes` return multiple routes. so I guess the API is different (at least the lnService API)?

reading from the documentation, it says for `getRouteToDestination`: 
> Call this iteratively after failed route attempts to get new routes

so I guess I can just do something like:
```
while success is false {
  getRouteToDestination(destination, tokens)
  success = probe
}
```

and each time getRouteToDestination will return a new route?

**Comment by alexbosworth** [comment]
> `getRoutes` return multiple routes. so I guess the API is different (at least the lnService API)?
> 
> reading from the documentation, it says for `getRouteToDestination`:
> 
> > Call this iteratively after failed route attempts to get new routes
> 
> so I guess I can just do something like:
> 
> ```
> while success is false {
>   getRouteToDestination(destination, tokens)
>   success = probe
> }
> ```
> 
> and each time getRouteToDestination will return a new route?

`getRoutes`, doesn't actually return more than 1 route in versions of LND later than 0.8.2

Yes as you probe, your database will be updated to ignore certain paths for a while and so a subsequent call to getRouteToDestination will return a different path to attempt based on that new state

**Comment by nicolasburtey** [comment]
ok got it. thanks.
