### ISSUE TITLE
probeForRoute issue

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#131]
I'm calling ProbeForRoute with the following parameters: 

```
      destination: '0291f76e4d8395fad2a58635d47d3f68cb8421fbadc47c76115d48a337c7df397d',
      lnd: {
        autopilot: ServiceClient
...
...
      },
      tokens: 1000,
      routes: [],
      payment: '54cef7f9591d443230345bb8a79176d0508f05da1c703ace97c108b8a8b1d232',
      cltv_delta: 40,
      features: [
        { bit: 9, is_known: true, is_required: false, type: 'tlv_onion' },
        {
          bit: 15,
          is_known: true,
          is_required: false,
          type: 'payment_identifier'
        },
        {
          bit: 17,
          is_known: true,
          is_required: false,
          type: 'multipath_payments_v0'
        }
      ],
      max_fee: 20
    }
```

and I get the following err:
```
    err: [
      503,
      "UnexpectedErrorWhenPayingViaRoute",
      {
        "err": {
          "code": 2,
          "metadata": {
            "_internal_repr": {},
            "flags": 0
          },
          "details": "missing total_msat"
        }
      }
    ]

```

on a lnd 0.11-beta. 

If I don't give `payment` as an argument, then I don't have this error.

After reading the lightning-rfc, It seems `payment` and `total_msat` are related for mpp. but I guess total_msat should be set automatically when payment is passed as an argument?

**Comment by alexbosworth** [comment]
You must pass `total_mtokens`

**Comment by nicolasburtey** [comment]
ok. that works.  thanks!

**Comment by nicolasburtey** [comment]
actually another question. isn't that mtokens should be 1000x tokens?

I have back `ExpectedEqualValuesForTokensAndMtokens`

**Comment by alexbosworth** [comment]
> actually another question. isn't that mtokens should be 1000x tokens?
> 
> I have back `ExpectedEqualValuesForTokensAndMtokens`

If there is an issue I would only pass one of the values, you do not need to pass both

**Comment by nicolasburtey** [comment]
ok

**Comment by nicolasburtey** [comment]
actually, if I have:

`mtokens` (only), I get:  `400,ExpectedTokensValueToProbeForRoute`
`tokens` (only), I get:  `missing total_msat`
both: `ExpectedEqualValuesForTokensAndMtokens` (I have done `mtokens: tokens * 1000`)

**Comment by alexbosworth** [comment]
Sorry, total_mtokens is separate, you must set that

But for mtokens vs tokens, only set one of those

So for tokens, set tokens=tokens and total_mtokens=mtokens

**Comment by alexbosworth** [comment]
Ah you're right there is an issue here

**Comment by alexbosworth** [comment]
I pushed a change to allow specifying mtokens only

You'll still want to specify total mtokens separately, this is for scenarios where the route is only one path of multiple, the total should be the sum of all, the mtokens is the individual path

**Comment by nicolasburtey** [comment]
I've upgraded to the last version. Still running into some issue. I'm setting both: `mtokens`, `total_mtokens` and `payment` and I have this error:

```
    err: [
      503,
      "UnexpectedErrorWhenPayingViaRoute",
      {
        "err": {
          "code": 2,
          "metadata": {
            "_internal_repr": {},
            "flags": 0
          },
          "details": "missing total_msat"
        }
      }
    ]
```

**Comment by alexbosworth** [comment]
OK I will take a look

**Comment by alexbosworth** [comment]
This is a new issue where `total_mtokens` wasn't being passed along - can you try master and see if it is fixed now?

**Comment by nicolasburtey** [comment]
this works. thanks!
