### ISSUE TITLE
incoming_peer typo?

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/ln-service#133]
for https://github.com/alexbosworth/ln-service/#payViaPaymentDetails:
>  `[incoming_peer]: <Pay Through Specific Final Hop Public Key Hex String>`

shouldn't this be:
`[incoming_peer__s__]: <Pay Through Specific __Initial__ Hop Public Key Hex String>`

?

**Comment by alexbosworth** [comment]
Initial? This control the final forwarding node, there can only be one with this API

**Comment by nicolasburtey** [comment]
yeah nevermind this is the `outgoing_channels` I had in mind. 

But there is no equivalent of incoming_peer in https://api.lightning.community/#sendpaymentv2 ?

**Comment by alexbosworth** [comment]
This value maps to last_hop_pubkey:

https://github.com/alexbosworth/lightning/blob/master/lnd_methods/offchain/subscribe_to_pay.js#L304

**Comment by nicolasburtey** [comment]
ok, thanks.

another question:

I don't see a way to pass a "`[payment]: <Payment Identifier Hex Encoded String>`" to `payViaPaymentDetails`

is there any reason for this? is it something that should be part of `messages`?

**Comment by alexbosworth** [comment]
I forget how this works, I think it may be impossible to pass this value on the LND side

**Comment by nicolasburtey** [comment]
ok. it seems payment is not really mandatory now, I'll investigate this later. thanks.
