### ISSUE TITLE
grpc errors on latest version

### ISSUE THREAD

**Issue by apotdevin** [alexbosworth/ln-service#134]
Updated to the latest version and i'm getting these errors:

```
 503,
  'FailedToRetrieveClosedChannels',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
```

```
503,
  'GetForwardingHistoryError',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
```

Haven't checked all the methods but might be happening with others as well.

Might it be related to the latest grpc-js change? It's a node running version 0.11.0

**Comment by alexbosworth** [comment]
Does it happen on node 0.12.0?

**Comment by apotdevin** [comment]
Unfortunately don't have any node running that version right now but can let you know when I do.

Still this would mean the version 0.11.0 is unsupported with this release?

**Comment by alexbosworth** [comment]
> Unfortunately don't have any node running that version right now but can let you know when I do.
> 
> Still this would mean the version 0.11.0 is unsupported with this release?

In theory grpc-js supports 0.10.0 and above, and grpc is deprecated, so that would set the lower bar

**Comment by apotdevin** [comment]
Tested, yeah same error:

```
2020-11-02 18:45:18 info [THUB]: {
    "probing": "carol 020782262fd78db8f3798624ad58d38e44bb3423e82a7a733d808e6f23449d38a3"
}
/Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /Users/potdevin/Documents/TH/thunderhub/node_modules/async/internal/onlyOnce.js:9:32
    at Object.callback (/Users/potdevin/Documents/TH/thunderhub/node_modules/lightning/lnd_methods/info/get_node.js:99:20)
    at Object.onReceiveStatus (/Users/potdevin/Documents/TH/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:173:36)
```

**Comment by apotdevin** [comment]
Had to revert to a previous version :( was getting this error randomly from all the calls

**Comment by alexbosworth** [comment]
> Had to revert to a previous version :( was getting this error randomly from all the calls

Not too surprised that there are random new errors, I'll try to see what can be done. I also see this error on node v12.19.0 but rarely

**Comment by alexbosworth** [comment]
You could also try using an older https://github.com/alexbosworth/lightning version to instantiate the `lnd` object, but using the latest `ln-service`

**Comment by apotdevin** [comment]
Will give it a try. Will also try that version, currently I'm on node v12.14.0 and its to many errors

**Comment by alexbosworth** [comment]
> Will give it a try. Will also try that version, currently I'm on node v12.14.0 and its to many errors

It might not work, I found that mixing and matching grpcs caused mysterious problems

**Comment by apotdevin** [comment]
Updating to node version 14 helped with all the errors, closing this
