### ISSUE TITLE
subscribeToPayViaRequest ignores max_fee_mtokens=0 (max_fee=0 works)

### ISSUE THREAD

**Issue by huumn** [alexbosworth/ln-service#141]
package.json
```json
"ln-service": "^51.7.0",
```

I was testing route finding failures in my LAPP with max_fee_mtokens=0 but the payment kept succeeding with fees. Setting max_fee=0 gave the expected behavior (routing failed).

**Comment by alexbosworth** [comment]
Did you pass 0 or '0'?

**Comment by huumn** [comment]
0. Went back and retested to make sure. The following succeeds with routing fees.

```javascript
        // create the payment, subscribing to its status
        const sub = subscribeToPayViaRequest({
          lnd,
          request: invoice,
          // can't use max_fee_mtokens https://github.com/alexbosworth/ln-service/issues/141
          // max_fee: Number(maxFee),
          max_fee_mtokens: 0,
          pathfinding_timeout: 30000
        })

```

**Comment by alexbosworth** [comment]
Ok yes that's because max fee mtokens must be a string and not a Number

I've added a check on this to error earlier

**Comment by huumn** [comment]
Ah! Good to know. I've probably made that same mistake elsewhere. Thank you!
