### ISSUE TITLE
Error getting node info in latest version

### ISSUE THREAD

**Issue by apotdevin** [alexbosworth/ln-service#143]
On a 0.12.1 node when fetching any nodes info I get:

![image](https://user-images.githubusercontent.com/31413433/124395067-5f17cb00-dd02-11eb-80d4-0f5c094a5f9b.png)

**Comment by apotdevin** [comment]
Node version 15.5.0

**Comment by alexbosworth** [comment]
How about if you do getWalletVersion()?
