### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by twshelton** [alexbosworth/ln-service#144]
I'm working on a PR for this repo and haven't been able to get the tests to run successfully.  Running the wallet-integration-tests results in this for all the tests:

I'm running an M1 Macbook with BTCD/LND running in docker.

Any thoughts?

` ``
FAIL  test/walletrpc-integration/test_sign_psbt.js
 ✖ spawn btcd ENOENT

  test: TAP
  at:
    line: 269
    column: 19
    file: internal/child_process.js
    function: Process.ChildProcess._handle.onexit
  errno: -2
  code: ENOENT
  syscall: spawn btcd
  path: btcd
  spawnargs:
    - --datadir
    - /var/folders/2q/pmv0hjf57dzgrjrnp522bfh40000gn/T/d205dc63-df01-472f-a326-2c697ebfa7b9
    - --debuglevel
    - trace
    - --listen
    - 127.0.0.1:14785
    - --logdir
    - /var/folders/2q/pmv0hjf57dzgrjrnp522bfh40000gn/T/d205dc63-df01-472f-a326-2c697ebfa7b9
    - --miningaddr
    - mhBh2rB9pqRuGsvqbPiCSM6A8xTXH2LXPx
    - null
    - --regtest
    - --relaynonstd
    - --rpccert
    - /var/folders/2q/pmv0hjf57dzgrjrnp522bfh40000gn/T/d205dc63-df01-472f-a326-2c697ebfa7b9/rpc.cert
    - --rpckey
    - /var/folders/2q/pmv0hjf57dzgrjrnp522bfh40000gn/T/d205dc63-df01-472f-a326-2c697ebfa7b9/rpc.key
    - --rpclisten
    - 127.0.0.1:14951
    - --rpcpass
    - 0k39BVOdg4uuS7qNCG2jbIXNpwU7d3Ft87PpHPPoCfk=
    - --rpcuser
    - bitcoinrpc
    - --txindex
  tapCaught: uncaughtException
```

**Comment by alexbosworth** [comment]
it will spawn btcd and lnd itself so maybe it's the docker aspect that is interfering?

**Comment by alexbosworth** [comment]
I have another project for using docker but it hasn't been integrated yet: https://github.com/alexbosworth/ln-docker-daemons

**Comment by twshelton** [comment]
I have shut down the docker processes and receive the same errors.

**Comment by alexbosworth** [comment]
Another thing I would check on is your path, like `which btcd` and `which lnd` to make sure the go binaries can be found in test execution

**Comment by twshelton** [comment]
ah, ok ... since those are running in Docker, I don't have the binaries locally.  This PR is simply exporting a reference to a  method in the the lightning package.  I have BTC/LND running in docker version and also on raspiblitz.  Could I simply run the tests from inside one of those environments?

**Comment by alexbosworth** [comment]
I'm not sure what you are writing but if you are writing something for the `lightning` package, the model there instead is to just use unit tests which don't require btcd/lnd

Otherwise I think you could use docker in various different ways but I'm not really a docker expert so not sure how to deploy it

**Comment by twshelton** [comment]
I was able to get the tests to run in the lightning package ... all good there.  I'll experiment with a couple of different options and see what I can find.

**Comment by alexbosworth** [comment]
I added the integration test here: https://github.com/alexbosworth/ln-service/blob/master/test/integration/test_get_wallet_status.js

**Comment by twshelton** [comment]
Much appreciated!!!!
