### ISSUE TITLE
Subscribing to invoices - event does not trigger for hodl invoices 

### ISSUE THREAD

**Issue by dannyjmac** [alexbosworth/ln-service#146]
I am subscribing to all invoices with `subscribeToInvoices`, the event for `invoice_updated` triggers when a hodl invoice is created and settled, but not for the initial payment or cancellation.

I was exepecting an update event when the invoice updates the `is_held`property from `undefined` to `true`, and/or when `is_cancelled` is updated from `undefined` to `true`

**Comment by alexbosworth** [comment]
lnd doesn't return those events on this subscription, so you'd have to create an issue on the lnd side for that

you can get this type of event only on individual invoices, with `subscribeToInvoice`

**Comment by dannyjmac** [comment]
Got it, thanks.
