### ISSUE TITLE
Is there a way to include metadata hash in createInvoice?

### ISSUE THREAD

**Issue by FilipChalupa** [alexbosworth/ln-service#148]
I'm implementing LNURL service but can't get over the `h` tag requirement. https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#requirements-3 The `h` tag is then required by a wallet. https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md#notes-on-metadata-for-server-side-lnurl-pay

Please is there a way to include metadata hash in an invoice using `ln-service` or am I trying to do something which is not yet possible?

**Comment by alexbosworth** [comment]
I think there are security concerns or something, I don't know

**Comment by FilipChalupa** [comment]
I don't doubt that.

I will investigate then. I hope I am on the right track looking into [alexbosworth/lightning/lnd_methods/invoices/create_invoice.js](https://github.dev/alexbosworth/lightning/blob/5e972f8f1daba1aefeb13e691a85efe7be2078e5/lnd_methods/invoices/create_invoice.js#L118-L118).

**Comment by FilipChalupa** [comment]
By diving deep into the [lnd](https://github.dev/lightningnetwork/lnd) I've found out that the answer was right under my nose. The `h` tag is sometimes called `description_hash` which is supported by `ln-service`. 🎉

**Comment by basharov** [comment]
> By diving deep into the [lnd](https://github.dev/lightningnetwork/lnd) I've found out that the answer was right under my nose. The `h` tag is sometimes called `description_hash` which is supported by `ln-service`. 🎉

Can you please share some code that could help us understand how you create a lnurl-pay flow if possible?
Thanks!

**Comment by alexbosworth** [comment]
you could look here https://github.com/alexbosworth/balanceofsatoshis/blob/master/lnurl/pay.js

**Comment by basharov** [comment]
@alexbosworth My problem is I'm trying to build a flow for lnurl pay but stuck with `description_hash`. 

Spec says it's sha256 of description or meta, but seems like I'm misunderstanding what value it should have exactly.

I asked on SO https://stackoverflow.com/questions/72366005/how-to-get-a-specific-hash-value-from-a-specific-string, and seemed like I got some clue but still not much luck.

When I try the flow via a mobile wallet like breez or BlueWallet, in most cases it shows "description has not found in invoice"

![image](https://user-images.githubusercontent.com/625090/170121200-7a076283-3f9b-4863-affa-2eca41e8974b.png)

![image](https://user-images.githubusercontent.com/625090/170121338-3d114c4d-b101-4452-a7df-744b99688169.png)

![image](https://user-images.githubusercontent.com/625090/170121367-cfc2765a-b26d-4d95-8ce4-1934bec91518.png)

When I decode the invoice with some online tools, I indeed don't see `h` in raw value and no `description_hash` in parsed one.

I tried to pass all kinds of data via sha257 utils, bech32 lib, converting from this to that and vice versa.

Can you advise in what direction I should move?

By the way I managed to implement lnurl withdraw flow and it works in the wallets I use.

**Comment by alexbosworth** [comment]
I'm not sure if I have an example for that other than the linked lnurl methods
