### ISSUE TITLE
Clarify and supplement invoice.is_confirmed given new final settle signal in LND

### ISSUE THREAD

**Issue by casey-bowman** [alexbosworth/ln-service#169]
Given the new code in LND v0.15.4-beta to signal final settlement, please clarify whether an invoice, when confirmed in the invoice subscription, is settled only in the old sense or if it is settled in the new final sense. If it is not in the new final sense, please add this to the invoice subscription.

See [htlcswitch: final settle signal PR](https://github.com/lightningnetwork/lnd/pull/6517/)

**Comment by casey-bowman** [comment]
Thank you for the added information :)

**Comment by casey-bowman** [comment]
I found [these tweets in a thread (not in order) by Joost Jager](https://twitter.com/joostjgr/status/1588188028035555331) helpful in understanding the problem - 

"Little known fact about lnd: if an invoice is reported to be settled, this only means that it was _requested_ to be settled. It will be settled eventually, but you may need to stay online or risk losing money👇"

"After settlement has been requested, both peers need to be online and connected to resolve the htlc on the commitment transaction. Otherwise the receiver must close on-chain before the htlc expires. If the receiver is down and does not close, the sender can claim back the funds."

"To address this, lnd 0.16 will contain a new api that provides insight into the final resolution of htlcs. It's another step in the maturation process of lightning. Use it to your advantage."

It sounds like what's there, at least in [v0.15.4-beta](https://github.com/lightningnetwork/lnd/releases/tag/v0.15.4-beta), is not sufficient for a new event in the invoices subscription.

**Comment by alexbosworth** [comment]
Yeah I think in the run up to lnd 0.16.0 i'll take a look at new APIs to assess what can be upgraded

There is already handling merged for some new events to make sure they don't mess up the existing APIs

**Comment by casey-bowman** [comment]
Also, the result of getPayment includes the method is_confirmed

> [is_confirmed]: <Payment Is Settled Bool>

Is this also tied to the state where the settlement has only been requested (as with the invoice subscription) or is it tied to the final settlement state ([after a check on the htlcs, per Joost Jager's edited comment on issue #6517](https://github.com/lightningnetwork/lnd/pull/6517/#issue-1229844699))?

**Comment by alexbosworth** [comment]
Probably it has a similar situation

Even if a payment is settled though, bear in mind that it could still go away in similar circumstances of not keeping your node online

Currently `is_confirmed` reflects the HTLC state, like do we have an HTLC where given time we can claim the money. This could be a problem if your node dies for some reason and you hit a timeout case, which in an invoice means you don't get the money after all or in a payment case means you didn't pay after all

But even with the "settled" API, it means that the money is added to your local balance on the channel, which itself has a timeout. If your node dies and that goes to chain and you stay offline, potentially the local balance also goes away which can mean that you don't get the money after all as well

So I don't think the current confirmation status in LND is misleading except in special cases like Joost's external tooling where he can take over invoice acceptance and other stuff

**Comment by casey-bowman** [comment]
Thank you for your detailed answer
