### ISSUE TITLE
waiting_close_channels is not obtainable through getPendingChannels

### ISSUE THREAD

**Issue by AmbossKeegan** [alexbosworth/ln-service#172]
_**Versions**_

lnd: 0.16.2-beta
bitcoind: 25.0.0
lightning: 9.4.0

_**Description**_

I would like to have access to the txid of the closing transaction. For example, in my screenshot below of ThunderHub, I have a pending close transaction, but no close_transaction_id on the response from getPendingChannels.

The channel is question for which I am looking to get a txid for, is within the `waiting_close_channels` array. `get_pending_channels` does return `pending_channels` but this does not include pending channels from the `waiting_close_channels` array.

I believe the fix needs to happen within this file: [get_pending_channels.js](https://github.com/alexbosworth/lightning/blob/572f9a02cae28594e8faa78ceb9841f04a563e6f/lnd_methods/offchain/get_pending_channels.js#L73)

`res` contains the property I want (`waiting_close_channels`) but the [function response](https://github.com/alexbosworth/lightning/blob/572f9a02cae28594e8faa78ceb9841f04a563e6f/lnd_methods/offchain/get_pending_channels.js#L81) only contains `pending_channels`.

<img width="1270" alt="Screen Shot 2023-06-06 at 12 57 55 PM" src="https://github.com/alexbosworth/ln-service/assets/132274422/705a790f-df00-4564-9518-75752cb0d4c6">

**Comment by alexbosworth** [comment]
please paste the result from res that you want to see represented?

**Comment by alexbosworth** [comment]
ok should be fixed now
