### ISSUE TITLE
Is there any way to get a list of **past** failed HTLCs

### ISSUE THREAD

**Issue by andreashuber69** [alexbosworth/ln-service#173]
IIUC, I can get failed HTLCs as they happen with [subscribeToForwards](https://github.com/alexbosworth/ln-service#subscribetoforwards). When I connect to a node I need a list of **past** failed HTLCs. Similar to [getFailedPayments](https://github.com/alexbosworth/ln-service#getfailedpayments) I would have expected a function **getFailedForwards** or something similar.

**Comment by alexbosworth** [comment]
no those aren't recorded by lnd for space savings reason
