### ISSUE TITLE
Some subscribeTo methods seem to keep a node process from shutting down

### ISSUE THREAD

**Issue by andreashuber69** [alexbosworth/ln-service#174]
```
import { subscribeToBlocks } from "lightning";
import { connectLnd } from "./test/connectLnd.js";

const eventName = "block";
const waitTime = 5000;

const authenticatedLnd = await connectLnd();
const emitter = subscribeToBlocks(authenticatedLnd);
const handler = (e) => console.log(e);

emitter.on(eventName, handler);
console.log(`Waiting for ${waitTime / 1000} seconds...`);
await new Promise((resolve) => setTimeout(resolve, waitTime));
console.log("Shutting down...");
emitter.off(eventName, handler);
```

Playing with lightning 9.8.1, the above code works as expected. That is, I get the following output and the process ends.

```
Waiting for 5 seconds...
{
  height: 798407,
  id: '00000000000000000004cf4fb091ef41647bd2d2e7657e2bd82a9158b8e165b6'
}
Shutting down...
```

However, when I use `subscribeToForwards` instead of `subscribeToBlocks` and set `eventName` to `forward` instead of `block`, the process hangs after logging `Shutting down...`. Why?

**Comment by andreashuber69** [comment]
Sorry, I meant to open this in https://github.com/alexbosworth/lightning, but I guess it applies to this project too.

**Comment by alexbosworth** [comment]
i think this is a node.js question? if you have open listeners node.js wouldn't exit right?

**Comment by andreashuber69** [comment]
> i think this is a node.js question? if you have open listeners node.js wouldn't exit right?

I would agree with you if the behavior was equivalent for `subscribeToBlocks` and `subscribeToForwards`. It clearly isn't, everything works as expected for the former but not for the latter.

Also, note that I remove the handler on the last line `emitter.off(eventName, handler);`

**Comment by alexbosworth** [comment]
Did you try using emitter.removeAllListeners() ?

**Comment by alexbosworth** [comment]
Hmm ok I guess it has an issue, can take a look

**Comment by alexbosworth** [comment]
Should be fixed now, can you try on the latest version?

**Comment by andreashuber69** [comment]
> import { subscribeToForwards } from "lightning";
> import { connectLnd } from "./test/connectLnd.js";
> 
> const eventName = "forward";
> const waitTime = 5000;
> 
> const authenticatedLnd = await connectLnd();
> const emitter = subscribeToForwards(authenticatedLnd);
> const handler = (e: unknown) => console.log(e);
> 
> emitter.on(eventName, handler);
> console.log(`Waiting for ${waitTime / 1000} seconds...`);
> await new Promise((resolve) => setTimeout(resolve, waitTime));
> console.log("Shutting down...");
> emitter.removeAllListeners();

I've tried with `subscribeToForwards`, `subscribeToPayments`, `subscribeToChannels` and they all now work as expected. Thank you!
