### ISSUE TITLE
Opening a channel should allow specifying the amount of the channel

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#5]
https://github.com/alexbosworth/ln-service/blob/d70d2508b66fc2b2da20857d0d2b0ede09040048/lightning/open_channel.js#L27

The REST interface should allow setting this value correct?  Can submit PR if so.

**Comment by alexbosworth** [comment]
Seems like it should yep

**Comment by alexbosworth** [comment]
Fixed by #7
