### ISSUE TITLE
lightning_daemon.js has a `createFromMetadataGenerator` call that doesn't appear to get evaluated

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#54]
Digging in to an issue where ln-service is running in a separate docker container from the lnd instance and trying to figure out why lnd is not responding, ran in to something that seems odd -

If I put a log on line 66 -
https://github.com/alexbosworth/ln-service/blob/master/lightning/lightning_daemon.js#L66

I see when creating the lightning daemon that the `macCreds` are returned but if I put a log on line 68 it never logs. I'm not sure what in the process makes that get called but it seemed like an odd behavior.

**Because of this I don't see where the macaroonData is ever added.**  I'm getting connection failures through grpc and trying to figure out why so this may be a red herring.

**Comment by alexbosworth** [comment]
It wouldn't be added if you were using the unlocker service

**Comment by PWKad** [comment]
This is when already unlocked and making a call such as `/v0/transactions`

**Comment by alexbosworth** [comment]
Wouldn't that be because the LND connection is cached by server.js?

**Comment by PWKad** [comment]
I don't think so.  Ex -

```
//...
    const macaroonData = Buffer.from(macaroon, 'base64').toString('hex');
    console.log(1)
    const macCreds = grpc.credentials.createFromMetadataGenerator((_, cbk) => {
      console.log(2)
      const metadata = new grpc.Metadata();

      metadata.add('macaroon', macaroonData);

      return cbk(null, metadata);
    });
    console.log(3)
    credentials = grpc.credentials.combineChannelCredentials(ssl, macCreds);
    break;
//...
```
In this situation the logs look like this - 

```
1
3
```
and 2 will never log

**Comment by alexbosworth** [comment]
I'm not sure when that callback is executed but it makes sense that if it's async it would be 1 3 2

**Comment by PWKad** [comment]
Related? https://github.com/grpc/grpc-node/issues/539#issuecomment-420146698

**Comment by alexbosworth** [comment]
I'm not sure

**Comment by PWKad** [comment]
I was able to figure out the connection issue but now I get an `expected 1 macaroon, got 0` error.  

The problem for connecting I mentioned before seems to be that lnd has a tls.cert that is generated for the ip address assigned from docker but when making the call through node-grpc something isn't liking the cert for the host being used.  When testing with the IP Address directly it works fine and I see the IP in the tls.cert. 

 I'm still trying to figure out why the rpc interface isn't responding in the local network but I'll close this for now, sorry for pestering.
