### ISSUE TITLE
it doesn't connect to daemon without passing tls and macaroon strings

### ISSUE THREAD

**Issue by grunch** [alexbosworth/ln-service#59]
I was using ln-service (v9.0.0) creating lightingDaemon passing only my LND dir, something like this
```
  lnd = lightningDaemon({
    host: LNR_LND_RPC_HOST,
  });
```
it worked perfect, I didn't need to encode to base64 because ln-service did it for me, but now with v20.0.0 it stopped to work, I started to check in the code and I see the `service/local_lnd.js` file is it there but not being used, now is forced to pass the macaroon and tls.cert as a base64 string, which I think is a step back, I don't know why.

I tried to added to the main index.js but it doesn't work, I get an promisify error, how we can fix this?
```
internal/util.js:257
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/home/grunch/dev/ln-rebalance/node_modules/ln-service/getChainBalance.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/grunch/dev/ln-rebalance/node_modules/ln-service/service/get_balance.js:3:25)
```

**Comment by alexbosworth** [comment]
The credentials were split up so there is a new env variable needed to specify which chain you are using

https://github.com/alexbosworth/ln-service#configuring-environment-variables

**Comment by grunch** [comment]
I know, I have configured that credentials, the issue is not allowed to use just indicate the path of my tls.cert, now is forced to enter the base64 string, previous versions let you do it in the two ways

**Comment by alexbosworth** [comment]
You can try service/local_lnd.js to retrieve the local LND via the path

**Comment by grunch** [comment]
I did, I told you in the first post, did you read it?

**Comment by grunch** [comment]
Maybe I didn't explained myself well, I added `service/local_lnd.js` to the main index.js, then imported to connect through it, but I get that promisify error I wrote up there

**Comment by alexbosworth** [comment]
I don't know what the code looks like but it seems like the require isn't specified correctly then, try the full relative path to the file and no destructuring

**Comment by grunch** [comment]
same thing

**Comment by alexbosworth** [comment]
I think it's because you're using promisify but this is not a callback function

**Comment by grunch** [comment]
```
#./index.js
....
const {updateRoutingFees} = require('./lightning');
const {verifyMessage} = require('./lightning');
const {localLnd} = require('./service'); <== added line

module.exports = {
  localLnd, <== added line
  addPeer,
  closeChannel,
.....
```

```
# my connect.js
const { localLnd } = require('ln-service');

const lnd = localLnd({});
```
I had all LND_GRPC_PORT, LND_HOST, LNSERVICE_LND_DIR, LNSERVICE_CHAIN, LNSERVICE_NETWORK vars setted.

**Comment by alexbosworth** [comment]
I tried exposing it now in index.js

**Comment by grunch** [comment]
@alexbosworth  why this was closed?

**Comment by alexbosworth** [comment]
This was exposed in index
