### ISSUE TITLE
WebSocket connections should not use Query Paramaters

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#68]
To connect to the web socket server currently it requires passing the rpcpassword or a secret as a query string param.

Since this is most likely saved by the servers the request goes across it opens up the adapter to mitm and other attacks.

This Stackoverflow answer provides some alternatives that I have not yet explored - https://stackoverflow.com/a/4361358/1200803

But it seems that setting it up using the basic authentication approach and then decoding the token in the `verify_client` would be safer.

I can PR this if agreed, else if this is not an issue let me know the proper way to connect to the web socket server.

**Comment by alexbosworth** [comment]
Sounds good

In theory the secret should go through HTTPS though, that way it is end-to-end encrypted

**Comment by alexbosworth** [comment]
Basic authentication will be just as vulnerable since the encoding there is simply base64

**Comment by PWKad** [comment]
But it automatically creates it as a header and removes it from the url, which it looks like you cannot do manually with the WebSocket object.

I've always been under the impression that the servers in between the browser for instance and the server that is servicing the request will save the entire url based on what I've always read, for ex. https://stackoverflow.com/a/2629241/1200803 but I'm no SSL expert so perhaps it's just a mis-understanding on my part.

**Comment by alexbosworth** [comment]
Intermediate servers can't cache data that's end-to-end encrypted and that includes both headers and query string params.

The part of the url that is not encrypted is the domain

**Comment by PWKad** [comment]
Fair enough

**Comment by alexbosworth** [comment]
I originally wanted to put the auth in the headers to be consistent with the normal auth for REST calls but there was some problem doing that, that's why I went to the query string method
