### ISSUE TITLE
Feature request: Balance by address?

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#76]
Would it make sense to take the output of `listchaintxns` and aggregate it to an address-based balance?  I am adding this as business logic already for an app so curious if you would want to add it as an data point returned from ln-service.

**Comment by alexbosworth** [comment]
Can you give an example? I don’t understand the use-case
-- 
Sent from my iPhone

**Comment by PWKad** [comment]
LND maintains a list of on-chain addresses currently in the DB that is only exposed when calling `lnd.getTransactions` and returns a list of addresses that have sent or received, which can be aggregated to get a list of addresses "used" by the lnd wallet.  

Currently there is no way to look at an address to get the balance besides calling `getTransactions`, aggregating the addresses, and then summing the values to end up with a balance by address.  When handling non-lightning interactions it's kind of a useful feature to return balance by address as a helper, but maybe keep it out of the ln-service until more feature requests would come in for it.

**Comment by alexbosworth** [comment]
two issues I can see:

1. The api doesn’t show much funds are assigned to which output
2. The api doesn’t show which utxos were used in each transaction

Are those problems?
-- 
Sent from my iPhone

**Comment by PWKad** [comment]
Hmm good point was digging in to see what you mean and it looks like the `getTransactions` call lacks what is needed here.  

Short of setting up each lnd address as a watch-only address for chain transaction monitoring I'm not sure what other way you would be able to handle this, may just need to fallback to using the bitcoin nodes' wallet for on-chain transactions.  May open an issue over on the lnd repo instead then.
