### ISSUE TITLE
Wrong comparison in range check

### ISSUE THREAD

**Issue by acrespo** [alexbosworth/ln-service#78]
https://github.com/alexbosworth/ln-service/blob/817ec56bec96e90ae5311f646bf0099bf5101f52/bolt11/hrp_as_tokens.js#L66

Shouldn't that check be against the maximum number of satoshis (`2100000000000`)? Isn't tokens unit `satoshis`? In that case, it will never be greater than `2100000000000`, right?

**Comment by alexbosworth** [comment]
Yeah should be compared to maxTokens

**Comment by acrespo** [comment]
I've created PR #79  addressing this.
