### ISSUE TITLE
Not getting invoice updates - Probably doing something dumb

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#82]
I'm trying to get subscribeToInvoices working and not getting anywhere, wanted to ask here and hope I realize I'm doing something dumb - 

I'm calling `subscribeToInvoices` with an instance of `local-lnd` to test connecting to the event emitter to be able to watch for invoices being paid and mark a message as such to broadcast it out through a separate open web socket (I do not want to blast all invoice updates to everyone obviously)

https://github.com/PWKad/proofof.chat/blob/master/logic-services/proofofchat-api/app.js#L56

I tried putting an event handler on the subscription - 
https://github.com/PWKad/proofof.chat/blob/master/logic-services/proofofchat-api/app.js#L60

and verified it fires properly by adding a timeout and manually calling `emit` to see data being broadcast.

I saw your message about it possibly being due to it being torn down but I tried creating invoices while putting a long timeout that emits at the end to make sure it didn't close and I never get any updates on creating invoices from LND.

I pulled latest and ran the test and everything looks good in the tests so wanted to see if possibly 

Is there anything that should be logged on the LND side when `ln-service`'s `subscribeToInvoice` method subscribes to LND of that grpc endpoint?  I don't see anything at all from LND besides the normal logs showing the invoice being generated.

Second set of eyes appreciated, I'm going to push this out as a neat little open source lightning chat app that uses the node's pubkey for authentication which is all working but I'm stuck trying to figure out how to get this subscription working.

**Comment by alexbosworth** [comment]
Even if there is a timeout, maybe the object is not being retained? Did you look at the test case for subscribe invoices?

**Comment by PWKad** [comment]
I did, I ran the tests and everything, the `EventEmitter` instance that is returned is the one I set a 10 second time out on and then emitted a message to make sure it was still held in memory and then during that 10 seconds generated invoices and verified they were in the invoice db but never got anything to log from that event, only from the manual `emit` call later.

**Comment by alexbosworth** [comment]
Maybe your event emitter is retained but not the lnd subscription

**Comment by PWKad** [comment]
Good point let me inspect it further thanks for taking a look.

**Comment by PWKad** [comment]
The LND node itself was curiously started and running but failing to reach consensus and I did not see the error logs until I started generating blocks again.  Restarted LND and it fixed the issue and now I am seeing updates published.

**Comment by PWKad** [comment]
In case someone else comes along this issue LND logs `INVC: New invoice subscription client: id=x` when a client subscribes so you can check for it that way.

**Comment by alexbosworth** [comment]
If you've copied old setup code for regtest nodes, there's been a behavior change in LND where it will never sync to the chain on regtest unless you mine 1 block before starting LND

**Comment by PWKad** [comment]
Yeah I have usually noticed that in the past but every the grpc calls were successful so it was a bit tricky to debug.  I usually have a helper running generating blocks every 10 seconds for regtest just didn't have it enabled :/  So many moving parts >.<

**Comment by alexbosworth** [comment]
In this behavior change even if you generate blocks after, it won't help

**Comment by awb99** [comment]
I have a similar issue: I am subscribing to invoices. Then I create an invoice via api, and was expecting to get the invoice event emitter triggered, but it doesn't. However, my BTCD is still
not completely synced. Can this be the issue?

**Comment by PWKad** [comment]
Yeah you shouldn't really interact with lnd until you are synced up.

**Comment by awb99** [comment]
Thanks!
