### ISSUE TITLE
Invoice macaroon - Non custodial use

### ISSUE THREAD

**Issue by whiteyhat** [alexbosworth/ln-service#87]
Hey Alex!

Is it possible to implement the Invoice macaroon to provide a non-custodial service where clients add their admin macaroon from the front so they can use their nodes?

**Comment by alexbosworth** [comment]
I don't think so, for non-custodial people should really run their own nodes and not share their admin macaroon with anyone

**Comment by whiteyhat** [comment]
Sorry @alexbosworth, I meant the `Invoice Macaroon`

**Comment by alexbosworth** [comment]
Sure you can use this with the invoice macaroon

**Comment by whiteyhat** [comment]
So, then the custodial element can be removed using `ln-service` by providing:

`gRPC Endpoint`
`Invoice macaroon`
`TLS Certificate`

So, I can allow users to operate invoices from their nodes, right?

**Comment by alexbosworth** [comment]
Yeah

**Comment by whiteyhat** [comment]
Great!
