### ISSUE TITLE
CBK is not a function - Signature using promises

### ISSUE THREAD

**Issue by whiteyhat** [alexbosworth/ln-service#88]
Hi @alexbosworth, I am trying to get verify a signature using `ln-service`. It does not seem to have a good syntax, otherwise the error `cbk is not a function` would not be reported.

```javascript
LndService.getLndInstance().then(function (data) {
                lnService.verifyMessage(data, msg, data.signature).finally(function (data) {
                console.log(data)
            })
```

As a background, this is how the `getLndInstance()` works:
```javascript
async getLndInstance(){
        if(lndInstance == null){
            lndInstance = await lnService.lightningDaemon({
                socket: this.getNodeAddress(),
                macaroon: Env.get('LND_MACAROON'),
            });
        }
        return lndInstance
    }
```

**Comment by whiteyhat** [comment]
The `getLndInstance` works perfectly, as it has been well tested to generate invoices

**Comment by alexbosworth** [comment]
You don't need to await lnService.lightningDaemon - that returns immediately

**Comment by whiteyhat** [comment]
Oh, so It is `lnService.lightningDaemon` instead of `await lnService.lightningDaemon`?

**Comment by whiteyhat** [comment]
If I modify it without using the promise it would still return me the error `cbk is not a function`

#### Code:
```
const publicKey = await lnService.verifyMessage(LndService.getLndInstance(), msg, data.signature)
console.log(publicKey)
```

**Comment by alexbosworth** [comment]
Yeah it's just a regular method that returns an object.

When you pass it to verifyMessage though you are going to have to pass an object with attributes

```
await verifyMessage({
    lnd: <LND GRPC API Object>
    message: <Message String>
    signature: <Signature String>
})
```

**Comment by whiteyhat** [comment]
I am passing the three objects but it does not seem to work..

I have `console.log` the message and the signature. Both results were as expected.

When I `console.log` the `LND GRPC API Object` this is the outcome
```javascript
info: undefined {"$interceptors":[],"$interceptor_providers":[],"$channel":{}}
```

info: undefined {"$interceptors":[],"$interceptor_providers":[],"$channel":{}}

**Comment by alexbosworth** [comment]
What's the error?

**Comment by whiteyhat** [comment]
```javascript
cbk is not a function
```

**Comment by alexbosworth** [comment]
Take a look on how to call it in the test here: https://github.com/alexbosworth/ln-service/blob/master/test/integration/test_verify_message.js

**Comment by whiteyhat** [comment]
This example helped to fix my issue and I achieved lo do digital signatures seamlessly!

Here it is the outcome [https://twitter.com/SatoshisGames/status/1131166851164233728](https://twitter.com/SatoshisGames/status/1131166851164233728)

**Comment by alexbosworth** [comment]
I pushed a new version btw, instead of lnService.lightningDaemon it is now lnService.authenticatedLndGrpc and instead of returning an object directly the returned object is wrapped in an {lnd}, updated the examples and tests

**Comment by PWKad** [comment]
I'm also getting this error now when calling `getPayments` async at the moment when setting up on a new project, going to debug why because maybe an error is getting swallowed (or more than likely I'm doing something dumb)

**Comment by alexbosworth** [comment]
I am reworking the promises method, maybe I can improve the error reporting

**Comment by alexbosworth** [comment]
I pushed a reworked version of promises to consolidate things

Instead of having separate promisified methods for promises, now the regular callback functions also return promises if you omit the callback

I added examples on how to use the promise methods as well: https://github.com/alexbosworth/ln-service#all-methods
