### ISSUE TITLE
Get onchain address from pubkey

### ISSUE THREAD

**Issue by whiteyhat** [alexbosworth/ln-service#89]
Hi Alex, I have seen you have a function to get the wallet info `get_wallet_info.js`. But this requires the Authentication LND gRPC API Object. 

Is it possible to get the on-chain address from the pubkey?

**Comment by alexbosworth** [comment]
You need to call `create_chain_address` and that requires the authenticated lnd grpc api object as well

There's no way to go from the node pubkey to a chain address

**Comment by whiteyhat** [comment]
Right, it makes sense. Btw, do you know any web app that verifies if a lightning message has been signed?

**Comment by alexbosworth** [comment]
Every payment request is signed actually, so if you put a message in the description, that automatically signs that message with the node key

**Comment by whiteyhat** [comment]
Oh, interesting. I did not know that. But I meant if you know anything similar to [https://tools.qz.sg/](https://tools.qz.sg/) but for lightning messages signatures. 

(This can be easily done using `ln-service`, but just wondering if you know if someone has already created i)

**Comment by alexbosworth** [comment]
No I don't know of anything for that

htlc.me also uses the signature/verify flow for the network directory feature

**Comment by whiteyhat** [comment]
Great! I will buidl it! Thanks again Alex
