### ISSUE TITLE
Refactor existing calls to match updated grpc calls 

### ISSUE THREAD

**Issue by PWKad** [alexbosworth/ln-service#9]
I'm assuming you are still using the existing methods in other projects and that is why some of the calls are named differently (ex. `add_peer` vs `connect_peer`)

If it is agreeable I can update the methods and calls to use the new names.

**Comment by PWKad** [comment]
Doh I just realized that LND has an undocumented REST API already...  I'm questioning whether it makes sense to fully build out this as a package now...

**Comment by alexbosworth** [comment]
Yes, it has one - plus GRPC is pretty cool :D

**Comment by alexbosworth** [comment]
The reason I don't use LND's naming is really two reasons: LND has changed naming over time, and I have my own ideas for naming and arrangement of data

**Comment by PWKad** [comment]
Yeah I was thinking about it too and I think there are still benefits to having this as a package for speed of development as well.  I do like GRPC but I've not messed with the LND REST API yet.

**Comment by alexbosworth** [comment]
The one change I want to make is that you can npm install this and then require and call the lightning/ directory functions directly which would use GRPC

**Comment by PWKad** [comment]
I'm almost finished with a front-end app that runs on top of it to finish testing out all of the calls.  After that I can see what else would be needed to use the services in the `/lightning` directory.

I set up the package.json so that you should be able to just `npm publish` it.  The only reason I didn't do any of that yet is because it would register under my npm account instead of yours.

**Comment by alexbosworth** [comment]
I just need to define a main script in the package and have that main file export the lightning directory functions, but I haven't made it that far yet, and it also needs to have some solution for the streaming APIs

**Comment by PWKad** [comment]
Closed by a847a8e14aaf5e2121b2efd647ad370be740d369
