### ISSUE TITLE
Verify message using mobile node

### ISSUE THREAD

**Issue by whiteyhat** [alexbosworth/ln-service#93]
Hey 👋 

Currently, all nodes connected with Lightning Joule can write and verify messages perfectly. However, there are some cases where nodes happen to have an issue when calling  `verify_message.js`.

On the @mandelmonkey case. when he writes messages on lightning and then calls `verify_message.js`. He can not get his `pubkey.signed_by`.

Now, using raw `LND GRPC` he gets the following body:
```javascript
{
valid: false,
pubkey: <PUBKEY_HERE>
```

I guess `LN-SERVICE` restricts every object from `LND GRPC` where the `valid=false`

**Comment by mandelmonkey** [comment]
yeah so mobile nodes are private hence valid would be false, it seems like maybe this library is not returning the pubkey when valid is false?

**Comment by whiteyhat** [comment]
> yeah so mobile nodes are private hence valid would be false, it seems like maybe this library is not returning the pubkey when valid is false?

I am 90% secure of this being the case. What do you think @alexbosworth ?

**Comment by whiteyhat** [comment]
> > yeah so mobile nodes are private hence valid would be false, it seems like maybe this library is not returning the pubkey when valid is false?
> 
> https://github.com/alexbosworth/ln-service/blob/bbc35741b0500778434c27240c562ba867a7a859/lightning/verify_message.js#L50
> 
> Can I PR?

https://github.com/alexbosworth/ln-service/pull/94

**Comment by alexbosworth** [comment]
Does valid really mean "public node"?

**Comment by mandelmonkey** [comment]
@alexbosworth I think valid is true when the node is in the graph, a mobile node only has private channels so would not be

https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L1214

but not sure why the node not been in the graph would mean the signature isnt valid?

**Comment by alexbosworth** [comment]
so valid should probably be called something else

why is it even important that the node is in the network graph?

**Comment by mandelmonkey** [comment]
Yep that’s what I was thinking I guess someone at lightning labs would know the reason?
