### ISSUE TITLE
Dockerizing a project containing ln-service

### ISSUE THREAD

**Issue by whiteyhat** [alexbosworth/ln-service#95]
Hey 👋 

I tried to dockerize a project with containing the npm packacge on `ln-service` but the `grpc` module is giving me an error that I do not know how to fix it.
 ```console
error /app/node_modules/ln-service/node_modules/grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments: 
Directory: /app/node_modules/ln-service/node_modules/grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.6.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/app/node_modules/ln-service/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" (not found)
```

**Comment by whiteyhat** [comment]
Forcing to have the latest version of `ln-services` fixes this issue

**Comment by whiteyhat** [comment]
It seems there is an issue with `LN-SERVICE` which affects the dockerization process. It keeps finding a different version to load the `gRPC` binary module used.

##### Error log
```console
Error: Failed to load gRPC binary module because it was not installed for the current system
web_1    | Expected directory: node-v72-linux-x64-glibc
web_1    | Found: [node-v64-darwin-x64-unknown]
web_1    | This problem can often be fixed by running "npm rebuild" on the current system
web_1    | Original error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
web_1    | Require stack:
web_1    | - /app/node_modules/grpc/src/grpc_extension.js
web_1    | - /app/node_modules/grpc/src/client_interceptors.js
web_1    | - /app/node_modules/grpc/src/client.js
web_1    | - /app/node_modules/grpc/index.js
web_1    | - /app/node_modules/ln-service/grpc/authenticated_lnd_grpc.js
web_1    | - /app/node_modules/ln-service/grpc/index.js
web_1    | - /app/node_modules/ln-service/index.js
web_1    | - /app/start/socket.js
web_1    | - /app/node_modules/@adonisjs/ignitor/src/Ignitor/index.js
web_1    | - /app/node_modules/@adonisjs/ignitor/index.js
web_1    | - /app/server.js
```

**Comment by whiteyhat** [comment]
Hey 👋 

@alexbosworth any ideas on this issue? Also @nicolasdorier any success on dockerizing this package?

**Comment by alexbosworth** [comment]
I haven't played around with Docker myself so I can't really say what is wrong

`npm rebuild` didn't work?

**Comment by whiteyhat** [comment]
Here it seems to be an issue when installing `ln-service` because of the `GRPC` library. Since it is expecting a Linux versión but funds the Mac OS version. 

I don’t think I can run `npm rebuild` because this is a docker image. The content from the docker image is:

```
# 1. Grab the latest node image
FROM node:latest
# 2. Set the working directory inside the container to /app
WORKDIR /app
# 3. Add the .env to the directory (We need those variables)
ADD .env /app
# 4. Expose port defined in .env file
EXPOSE ${PORT}
# 5. Add package.json to the directory
ADD package.json /app
# 6. Install dependencies
RUN yarn  
# 7. Copy the rest into directory
COPY . /app
# 8. Start the app inside the container
CMD ["yarn", "start"]
```

**Comment by NicolasDorier** [comment]
I have been dockerizing lot's of npm project that may or may not use this library. (RTL, Lightning Charge, Spark)

I don't remember having any issue, you should take a look at the docker file there.

**Comment by NicolasDorier** [comment]
sorry actually only RTL might use this lib, there rest is clightning.

**Comment by alexbosworth** [comment]
Can you make the docker script run npm install itself to get the correct package for itself?

**Comment by whiteyhat** [comment]
> sorry actually only RTL might use this lib, the rest is clightning.

@NicolasDorier would you mind sharing the docker image where you include this package 😃

**Comment by NicolasDorier** [comment]
https://github.com/ShahanaFarooqui/RTL/blob/master/Dockerfile

**Comment by NicolasDorier** [comment]
mmh it does not seem to use this package though? It is strange.

**Comment by whiteyhat** [comment]
> Can you make the docker script run npm install itself to get the correct package for itself?

I have added an `npm rebuild` after the install but it does not seem to work either. I can not find a potential solution to overcome this issue to successfully create a docker image for this package..

**Comment by alexbosworth** [comment]
Maybe remove the package-lock.json and node_modules dir and then npm install?

**Comment by whiteyhat** [comment]
I found a potential fix. This is my code for the `yarn.lock`:
```json
ln-service@^41.1.0:
  version "41.1.0"
  resolved "https://registry.yarnpkg.com/ln-service/-/ln-service-41.1.0.tgz#1f422f62c173540da3d285a4a8b446476aa62a8e"
  integrity sha512-SgBq+vF2IVMjUrrqrn/1uoHLrdIhIUg4B3uV2naYWrF7dof8mU+qifUbXQSrv6iWFMjCIGws8JlyD3Qrz5/6kw==
  dependencies:
    "@datastructures-js/priority-queue" "1.0.2"
    "@grpc/proto-loader" "0.5.1"
    async "3.1.0"
    asyncjs-util "1.1.1"
    basicauth-middleware "3.1.0"
    bech32 "1.1.3"
    bitcoinjs-lib "5.1.2"
    bn.js "5.0.0"
    body-parser "1.19.0"
    bolt07 "1.4.2"
    compression "1.7.4"
    cors "2.8.5"
    dotenv "8.0.0"
    express "4.17.1"
    grpc "1.22.2"
    is-base64 "0.1.0"
    is-hex "1.1.3"
    lodash "4.17.15"
    morgan "1.9.1"
    promptly "3.0.3"
    request "2.88.0"
    safe-compare "1.1.4"
    secp256k1 "3.7.1"
    ws "7.1.1"
```
however, because I am using `iOS` docker-compose.yml can not find the `linux` version. As it keeps finding this version:`/app/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node` If you run `linux` could you send me your ln-service code block from your `yarn.lock` or `package-lock.json`

**Comment by whiteyhat** [comment]
> It seems there is an issue with `LN-SERVICE` which affects the dockerization process. It keeps finding a different version to load the `gRPC` binary module used.
> 
> ##### Error log
> ```
> Error: Failed to load gRPC binary module because it was not installed for the current system
> web_1    | Expected directory: node-v72-linux-x64-glibc
> web_1    | Found: [node-v64-darwin-x64-unknown]
> web_1    | This problem can often be fixed by running "npm rebuild" on the current system
> web_1    | Original error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
> web_1    | Require stack:
> web_1    | - /app/node_modules/grpc/src/grpc_extension.js
> web_1    | - /app/node_modules/grpc/src/client_interceptors.js
> web_1    | - /app/node_modules/grpc/src/client.js
> web_1    | - /app/node_modules/grpc/index.js
> web_1    | - /app/node_modules/ln-service/grpc/authenticated_lnd_grpc.js
> web_1    | - /app/node_modules/ln-service/grpc/index.js
> web_1    | - /app/node_modules/ln-service/index.js
> web_1    | - /app/start/socket.js
> web_1    | - /app/node_modules/@adonisjs/ignitor/src/Ignitor/index.js
> web_1    | - /app/node_modules/@adonisjs/ignitor/index.js
> web_1    | - /app/server.js
> ```

## Context
This was the original error where it finds my `grpc` library for `node-v64-darwin-x64-unknown` but it is required to have `node-v72-linux-x64-glibc`to build a successful docker container with `docker-compose.yml`

**Comment by dennisreimann** [comment]
> Found: [node-v64-darwin-x64-unknown]

This indicates that you are running `npm install` on a architecture that's different from the one used by the docker container. Have you tried copying your apps files over to the container and installing the dependencies there?

The grpc package has native extensions which need to be build on/for the architecture the app is running on.

**Comment by whiteyhat** [comment]
All good when I run a fresh `npm install` and creates a `packge-json.lock` from a Linux OS
