### ISSUE TITLE
Allow gRPC access over HTTP if .onion

### ISSUE THREAD

**Issue by NicolasDorier** [alexbosworth/ln-service#96]
We noticed that wallets using gRPC does not work over Tor because all libraries using gRPC assume HTTPS is used. As a result, only REST wallets works.

https://github.com/btcpayserver/btcpayserver-docker/issues/170

**Comment by alexbosworth** [comment]
Is it secure to use HTTP? Forgive my ignorance on the subject, but can you not just use HTTPS with Tor?

**Comment by NicolasDorier** [comment]
@alexbosworth Let's encrypt do not support https on tor. You can use HTTPS on Tor by buying a certificate, but this provide no additional security as Tor itself is end to end encrypted.

**Comment by alexbosworth** [comment]
It does sound like a good idea to me

**Comment by alexbosworth** [comment]
If you could provide me with an http endpoint I could try adding support, I'm not sure how to configure my lnd for this exactly

**Comment by NicolasDorier** [comment]
@alexbosworth apparently gRPC can't work without SSL layer because of its dependency on HTTP2.
However, Tor is never user along with HTTPS as it does not give any additional security. :(

**Comment by alexbosworth** [comment]
Are you sure about that? I see a createInsecure method on grpc so I think it is possible to use non SSL transport

**Comment by NicolasDorier** [comment]
@alexbosworth source: Twitter https://twitter.com/NicolasDorier/status/1157164784921403393

**Comment by NicolasDorier** [comment]
I can setup a server for you so you can try if you want.

**Comment by NicolasDorier** [comment]
actually @mandelmonkey  might have one? Would you mind to share?

**Comment by alexbosworth** [comment]
It would be helpful

**Comment by mandelmonkey** [comment]
@NicolasDorier how did you know that GRPC doesnt work with http1? it may jsut be a bug in grpc, https://github.com/grpc/grpc-java/issues/5998
im not sure but it doesnt explicitly say that grpc cant work with http1

@alexbosworth I only have a url for a mainnet node I use, I guess you just need to set up a testnet btcpay somewhere? @NicolasDorier is that possible to do?

**Comment by NicolasDorier** [comment]
@mandelmonkey I thought you got it already, will create one for alex.

**Comment by NicolasDorier** [comment]
@alexbosworth I sent you creds on twitter.

**Comment by mandelmonkey** [comment]
@NicolasDorier I only have mainnet one which was my personal btcpay server

**Comment by NicolasDorier** [comment]
Closing this, as discussed with @alexbosworth , it is impossible to pass macaroon via gRPC on http.

**Comment by alexbosworth** [comment]
I'll think more about how to enable methods towards a Tor endpoint but yeah it's not so straightforward

**Comment by huumn** [comment]
Any update on this? Why is it impossible?

**Comment by alexbosworth** [comment]
> Any update on this? Why is it impossible?

it's not how gRPC is designed, but maybe it is possible

You could also use something like https://github.com/openoms/bitcoin-tutorials/blob/master/tor2ip_tunnel.md

**Comment by huumn** [comment]
Thank you. I will try to see if I can workaround it.
